name: Run Selenium & API Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  AutomationTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Latest Test Image
        run: docker pull moslemasaad/gitea-test-automation

      - name: Run Automation Tests with Docker Compose
        run: |
          cd Gitea-Test-Automation
          docker-compose up --build --abort-on-container-exit

      - name: Show Logs if Tests Fail
        if: failure()
        run: |
          cd Gitea-Test-Automation
          docker logs selenium-test-runner || true
          docker logs api-test-runner || true

      - name: Stop and Remove Containers
        run: |
          cd Gitea-Test-Automation
          docker-compose down
